### ISSUE TITLE
Build script does not work with local dependencies

### ISSUE THREAD

**Issue by abelmokadem** [costastf/python_project#7]
Put something like this in your pipfile:

```
bootstrapperlib = {path = '/foo/bar/my-lib', editable = true}
```

Run build script

```
Traceback (most recent call last):
  File "_CI/scripts/build.py", line 71, in <module>
    raise SystemExit(not build())
  File "_CI/scripts/build.py", line 53, in build
    save_requirements()
  File "/Users/abelmokadem/Projects/gitlab/bootstrappercli/_CI/library/library.py", line 380, in save_requirements
    top_level_packages, top_level_dev_packages = get_top_level_dependencies()
  File "/Users/abelmokadem/Projects/gitlab/bootstrappercli/_CI/library/library.py", line 335, in get_top_level_dependencies
    packages = [Package(name_, version_) for name_, version_ in pip_packages]
  File "/Users/abelmokadem/Projects/gitlab/bootstrappercli/_CI/library/library.py", line 335, in <listcomp>
    packages = [Package(name_, version_) for name_, version_ in pip_packages]
  File "/Users/abelmokadem/Projects/gitlab/bootstrappercli/_CI/library/library.py", line 80, in __init__
    self.comparator, self.version = self._decompose_full_version(full_version)
  File "/Users/abelmokadem/Projects/gitlab/bootstrappercli/_CI/library/library.py", line 94, in _decompose_full_version
    if full_version.startswith(operator):
AttributeError: 'dict' object has no attribute 'startswith'
```

**Comment by costastf** [comment]
I don't think it's worth fixing this, it would be better to update the template to not use requirements.txt since that is not needed any more.
